/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;


import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.animation.Animation;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import com.itextpdf.text.Document;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import javax.swing.JFileChooser;
//import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hp
 */
public class homepage extends javax.swing.JFrame {
     Connection con;
    PreparedStatement statement;
    Statement st;
    String cs;
    boolean next;
    String password;

    String query;
    ResultSet rs;
    ResultSet rs1;
    ResultSet rs2;
    String user;
    boolean nxt;
    boolean prev;
    String name;
    String iddate;

    /**
     * Creates new form homepage
     */
    public homepage() {
        
         con = null;
        st = null;
        statement = null;
        next = false;
        cs = "jdbc:mysql://localhost:3306/dairy_project";

        password = "";
        user = "root";
        initComponents();
        this.setLocationRelativeTo(null);
       menubar.setSize(210, 552);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        mainpanel = new javax.swing.JPanel();
        menubar = new javax.swing.JPanel();
        welcomelabel = new javax.swing.JLabel();
        lnamelabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        registerseller = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sellname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sellphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sellAddress = new javax.swing.JTextField();
        msgsell = new javax.swing.JLabel();
        msgsell1 = new javax.swing.JLabel();
        profilepanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        profileimage = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        Reportpanel = new javax.swing.JPanel();
        labelimage = new javax.swing.JLabel();
        milk = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        customerphone = new javax.swing.JTextField();
        today = new javax.swing.JLabel();
        currenttime1 = new javax.swing.JLabel();
        today1 = new javax.swing.JLabel();
        today2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        mng = new javax.swing.JTextField();
        today3 = new javax.swing.JLabel();
        even = new javax.swing.JTextField();
        viewseller = new javax.swing.JPanel();
        searchseller = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        currenttime = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setLayout(null);

        menubar.setBackground(new java.awt.Color(73, 102, 70));

        javax.swing.GroupLayout menubarLayout = new javax.swing.GroupLayout(menubar);
        menubar.setLayout(menubarLayout);
        menubarLayout.setHorizontalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        menubarLayout.setVerticalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        mainpanel.add(menubar);
        menubar.setBounds(0, 0, 188, 480);

        welcomelabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        welcomelabel.setForeground(new java.awt.Color(0, 102, 51));
        welcomelabel.setText("Welcome");
        mainpanel.add(welcomelabel);
        welcomelabel.setBounds(220, 20, 170, 40);

        lnamelabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lnamelabel.setForeground(new java.awt.Color(0, 102, 51));
        lnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnamelabel.setText("Welcome");
        mainpanel.add(lnamelabel);
        lnamelabel.setBounds(550, 20, 150, 40);

        namelabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        namelabel.setForeground(new java.awt.Color(0, 102, 51));
        namelabel.setText("Welcome");
        mainpanel.add(namelabel);
        namelabel.setBounds(390, 20, 160, 40);

        registerseller.setBackground(new java.awt.Color(255, 255, 255));
        registerseller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        registerseller.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Register a seller/customer");
        registerseller.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 494, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name:");
        registerseller.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 95, 101, 36));

        sellname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sellname.setForeground(new java.awt.Color(0, 153, 51));
        sellname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        registerseller.add(sellname, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 102, 331, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Phone Number:");
        registerseller.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 152, 119, 36));

        sellphone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sellphone.setForeground(new java.awt.Color(0, 153, 51));
        sellphone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        registerseller.add(sellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 158, 322, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Address:");
        registerseller.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 203, 119, 36));

        sellAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sellAddress.setForeground(new java.awt.Color(0, 153, 51));
        sellAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        registerseller.add(sellAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 209, 322, -1));

        msgsell.setBackground(new java.awt.Color(255, 255, 255));
        msgsell.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        msgsell.setForeground(new java.awt.Color(0, 153, 0));
        registerseller.add(msgsell, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 490, 60));

        msgsell1.setBackground(new java.awt.Color(255, 255, 255));
        msgsell1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        msgsell1.setForeground(new java.awt.Color(0, 153, 0));
        registerseller.add(msgsell1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 354, 480, 60));

        profilepanel.setBackground(new java.awt.Color(255, 255, 255));
        profilepanel.setForeground(new java.awt.Color(0, 153, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("First Name:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 51));
        jLabel12.setText("Last Name:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 51));
        jLabel13.setText("Email:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 51));
        jLabel14.setText("Date of Birth:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 51));
        jLabel15.setText("Telephone:");

        fname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 153, 0));

        lname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lname.setForeground(new java.awt.Color(0, 153, 51));

        dob.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dob.setForeground(new java.awt.Color(0, 153, 0));
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });

        tel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tel.setForeground(new java.awt.Color(0, 153, 0));
        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 153, 51));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        profileimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/user.png"))); // NOI18N

        image.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        image.setForeground(new java.awt.Color(0, 204, 102));
        image.setText("update Profile Image");
        image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout profilepanelLayout = new javax.swing.GroupLayout(profilepanel);
        profilepanel.setLayout(profilepanelLayout);
        profilepanelLayout.setHorizontalGroup(
            profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilepanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilepanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileimage, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(profilepanelLayout.createSequentialGroup()
                            .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                            .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(198, 198, 198))
                        .addGroup(profilepanelLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)))))
        );
        profilepanelLayout.setVerticalGroup(
            profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilepanelLayout.createSequentialGroup()
                .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilepanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(profilepanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(profileimage, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)))
                .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        registerseller.add(profilepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        mainpanel.add(registerseller);
        registerseller.setBounds(50, 50, 770, 500);

        Reportpanel.setBackground(new java.awt.Color(255, 255, 255));
        Reportpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        javax.swing.GroupLayout ReportpanelLayout = new javax.swing.GroupLayout(Reportpanel);
        Reportpanel.setLayout(ReportpanelLayout);
        ReportpanelLayout.setHorizontalGroup(
            ReportpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        ReportpanelLayout.setVerticalGroup(
            ReportpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        mainpanel.add(Reportpanel);
        Reportpanel.setBounds(200, 20, 530, 350);

        labelimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/QOD2.jpg"))); // NOI18N
        mainpanel.add(labelimage);
        labelimage.setBounds(0, 80, 840, 430);

        milk.setBackground(new java.awt.Color(255, 255, 255));
        milk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        milk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PhoneNumber");
        milk.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Name");
        milk.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/zoom.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        milk.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 70, 60));

        search1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        search1.setForeground(new java.awt.Color(0, 153, 0));
        search1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        milk.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 40));

        name1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name1.setForeground(new java.awt.Color(0, 153, 51));
        name1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        milk.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 330, 20));

        customerphone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        customerphone.setForeground(new java.awt.Color(0, 153, 51));
        customerphone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        milk.add(customerphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 330, 20));

        today.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        today.setForeground(new java.awt.Color(0, 153, 0));
        today.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        today.setText("Total:");
        milk.add(today, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 100, 40));

        currenttime1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        currenttime1.setForeground(new java.awt.Color(255, 0, 0));
        currenttime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milk.add(currenttime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 290, 40));

        today1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        today1.setForeground(new java.awt.Color(0, 153, 0));
        today1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        today1.setText("Today:");
        milk.add(today1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 140, 40));

        today2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        today2.setForeground(new java.awt.Color(0, 153, 0));
        today2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        today2.setText("Morning:");
        milk.add(today2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 110, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Litres_Brought");
        milk.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, 30));

        total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        milk.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 90, 30));

        mng.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mng.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        milk.add(mng, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 90, 30));

        today3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        today3.setForeground(new java.awt.Color(0, 153, 0));
        today3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        today3.setText("Evening:");
        milk.add(today3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 100, 40));

        even.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        even.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        milk.add(even, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 90, 30));

        mainpanel.add(milk);
        milk.setBounds(220, 0, 630, 590);

        viewseller.setBackground(new java.awt.Color(255, 255, 255));
        viewseller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        viewseller.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchseller.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchseller.setForeground(new java.awt.Color(0, 153, 0));
        searchseller.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        viewseller.add(searchseller, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 461, 47));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/zoom.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewseller.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 60, 60));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 153, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SellerID", "Name", "PhoneNumber", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable1);

        viewseller.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 620, 290));

        mainpanel.add(viewseller);
        viewseller.setBounds(190, 20, 630, 590);

        jPanel1.setBackground(new java.awt.Color(73, 102, 70));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUALITY ORGANIC DAIRY STAFF");

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/user.png"))); // NOI18N

        usernamelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernamelabel.setForeground(new java.awt.Color(255, 255, 255));
        usernamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        currenttime.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        currenttime.setForeground(new java.awt.Color(255, 204, 204));
        currenttime.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(currenttime, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(profile)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(currenttime, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void fetch() throws ClassNotFoundException{
    try{
            Class.forName("com.mysql.jdbc.Driver");
            
            con=DriverManager.getConnection(cs,user,password);
            st= con.createStatement();
            query="select * from seller";
             
            ResultSet rs = st.executeQuery(query);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            //JTableHeader  thead = jTable1.getTableHeader();
            //thead.setBackground(Color.GREEN);
            //thead.setForeground(Color.GREEN);

            
            } catch (SQLException ex) {
            Logger.getLogger(homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    int x;
   
    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
         
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void rSButtonMetro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro8ActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro8ActionPerformed

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
         Thread th = new Thread(){
      
            public void run(){
           try {
           for(int i =0;i <=210; i ++){
           Thread.sleep(5);
           i++;
           i++;
           i++;
           menubar.setSize(i,552);
           }
           
           }catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
           }
      }
       
       };th.start();
      
        menubar.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseClicked

    private void rSButtonMetro8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro8MouseClicked

    Thread th = new Thread(){
      
            public void run(){
           try {
           for(int i =210;i >= 0; i--){
           Thread.sleep(10);
           i--;
           i--;
           i--;
           menubar.setSize(i,552);
           }
           
           }catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
           }
      }
       
       };th.start();
       
       menubar.setVisible(true);
       
       
       
// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro8MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      name = usernamelabel.getText();
         
      try{
                Class.forName("com.mysql.jdbc.Driver");//registers drivers we configured
                con=DriverManager.getConnection(cs,user,password);
                st=con.createStatement();
                String a = " select Fname,Lname from register where username = '"+name+"'";
               //String b = " select Fname from register where username = '"+query1+"' AND password = '"+query2+"'";
               //String c = " select Lname from register where username = '"+query1+"' AND password = '"+query2+"'";
                rs= st.executeQuery(a);
                //rs2 = st.executeQuery(b);
                //rs3 = st.executeQuery(c);

                if(rs.next()){
                   namelabel.setText(rs.getString("Fname"));
                   lnamelabel.setText(rs.getString("Lname"));
                   
                }}catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
           }
       try{
                Class.forName("com.mysql.jdbc.Driver");//registers drivers we configured
                con=DriverManager.getConnection(cs,user,password);
                st=con.createStatement();
                String a = " select * from register where username = '"+name+"'";
               //String b = " select Fname from register where username = '"+query1+"' AND password = '"+query2+"'";
               //String c = " select Lname from register where username = '"+query1+"' AND password = '"+query2+"'";
                rs1= st.executeQuery(a);
                //rs2 = st.executeQuery(b);
                //rs3 = st.executeQuery(c);

                if(rs1.next()){
                  byte[] img = rs1.getBytes("profile");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myimg = im.getScaledInstance(profile.getWidth(), profile.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newimage = new ImageIcon(myimg);
                    profile.setIcon(newimage);
     }

    }catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
           }
                
        long millis = System.currentTimeMillis();
       java.sql.Date date = new java.sql.Date(millis);
       currenttime.setText(date.toString());
       currenttime1.setText(date.toString());
        menubar.setVisible(false);
       labelimage.setVisible(true);
       labelimage.setAlignmentX(CENTER_ALIGNMENT);
       registerseller.setVisible(false);
       viewseller.setVisible(false);
        milk.setVisible(false);
        Reportpanel.setVisible(false);
        profilepanel.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
       //menubar.setVisible(true);
    }//GEN-LAST:event_menuMouseExited

    private void rSButtonMetro8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro8MouseExited
   
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro8MouseExited

    private void viewprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewprofileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewprofileActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
          
        String name = sellname.getText();
        String phne = sellphone.getText();
        String add = sellAddress.getText();
        final Icon icon = new ImageIcon("check.jpg");
         
        if (name.isEmpty() && phne.isEmpty() && add.isEmpty()){
        JOptionPane.showMessageDialog(null,"Enter correct details!");
        sellname.requestFocus();
        }
        else if (name.isEmpty()|| phne.isEmpty()||add.isEmpty()){
            
           JOptionPane.showMessageDialog(null,"Missing Fields!");
           
        }
        else{

            try{
                Class.forName("com.mysql.jdbc.Driver"); //registers drivers we configured
                con=DriverManager.getConnection(cs,user,password);
                st=con.createStatement();
                query = "INSERT INTO seller(Name,PhoneNo,Address) VALUES('"+name+"','" +phne+"','" +add+"')";
                st.executeUpdate(query);//executes the activities

                /*String  seequery= "select username from register where username='"+usernametxt.getText()+"'";*/

                /*ResultSet uname=  st.executeQuery(seequery);
                uname.getString("username");*/

            
            msgsell.setText("Seller Registered successfully");
             sellname.setText("");
                sellphone.setText("");
                sellAddress.setText("");
                sellname.requestFocus();
                 
                
            }
            catch(SQLException ex){
                ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt

            }
            catch(ClassNotFoundException ex){
                ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt

            }
            finally
            {
                try
                {
                    if (st!=null)
                    {
                        st.close();
                    }

                    if(con!=null)
                    {
                        con.close();
                    }
                }
                catch(SQLException ex){
                    ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt
                }

            }
           
        }

// TODO add your handling code here:
    }//GEN-LAST:event_saveMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        sellname.setText("");
        sellphone.setText("");
        sellAddress.setText("");
        msgsell.setText("");
        sellname.requestFocus();
// TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        registerseller.setVisible(true);
        welcomelabel.setVisible(false);
        lnamelabel.setVisible(false);
         namelabel.setVisible(false);
        labelimage.setVisible(false);
        menubar.setVisible(false);
        viewseller.setVisible(false);
         //identity.setVisible(false);
          milk.setVisible(false);
          Reportpanel.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_registerMouseClicked

    private void rSButtonMetro9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro9MouseClicked
         DefaultTableModel model = ( DefaultTableModel) jTable1.getModel();
        try{
            int row = jTable1.getSelectedRow();
        String cell = jTable1.getModel().getValueAt(row, 0).toString();
             Class.forName("com.mysql.jdbc.Driver");
            
            con=DriverManager.getConnection(cs,user,password);
            
         query = "delete from seller where sellerId = "+cell+"";
        st = con.prepareStatement(query);
          st.executeUpdate(query);
        JOptionPane.showMessageDialog(null,"Record has been deleted successfully");
        fetch();
        } catch(Exception ex){
        ex.printStackTrace();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro9MouseClicked

    private void viewsellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewsellMouseClicked
         try {
                    fetch();
                }
         catch (ClassNotFoundException ex) {
                    Logger.getLogger(homepage.class.getName()).log(Level.SEVERE, null, ex);
                }
        viewseller.setVisible(true);
       registerseller.setVisible(false);
       welcomelabel.setVisible(false);
        lnamelabel.setVisible(false);
        labelimage.setVisible(false);
        menubar.setVisible(false);
        //identity.setVisible(false);
        namelabel.setVisible(false);
        milk.setVisible(false);
        Reportpanel.setVisible(false);
        profilepanel.setVisible(false);
       
// TODO add your handling code here:
    }//GEN-LAST:event_viewsellMouseClicked

    private void rSButtonMetro8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro8MouseEntered
       
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro8MouseEntered

    private void rSButtonMetro7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro7MouseClicked
        JDialog.setDefaultLookAndFeelDecorated(true);
    int response = JOptionPane.showConfirmDialog(null, "Do you really want to Logout?", "Confirm -Logout",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (response == JOptionPane.NO_OPTION) {
       
       
    } else if (response == JOptionPane.YES_OPTION) {
      login log = new login();
        log.setVisible(true);
        this.dispose();
    } else if (response == JOptionPane.CLOSED_OPTION) {
      
     
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro7MouseClicked

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        menubar.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_menuMouseEntered

    private void identityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_identityMouseClicked
     
       // TODO add your handling code here:
    }//GEN-LAST:event_identityMouseClicked

    private void identityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identityActionPerformed
    /*try{
           final String RESULT = "IdentityCard.pdf";
    Document document=new Document(PageSize.A4.rotate());
        PdfWriter.getInstance(document, new FileOutputStream(RESULT));
        document.open();      
        PdfPTable table = new PdfPTable(4);
      
          Class.forName("com.mysql.jdbc.Driver");//registers drivers we configured
        con=DriverManager.getConnection(cs,user,password);
        st=con.createStatement();
         

       
            query="select * from register";
            ResultSet rs=st.executeQuery(query); 
            table.addCell("RegId");
            table.addCell("FName");
            table.addCell("Lname");
            table.addCell("Email");
           
       while(rs.next()){
    
        table.addCell(new Phrase(rs.getString("RegId")));
        table.addCell(new Phrase(rs.getString("Fname")));
        table.addCell(new Phrase(rs.getString("Lname")));
        table.addCell(new Phrase(rs.getString("Email")));
        
              
     }
       document.add(table);
              if(Desktop.isDesktopSupported()){
                    File myfile = new File(RESULT);
                    Desktop.getDesktop().open(myfile);
        }
     
              
       }catch(Exception ex){
        ex.printStackTrace();
             }
    */
    }//GEN-LAST:event_identityActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        try{
            Class.forName("com.mysql.jdbc.Driver");

            con=DriverManager.getConnection(cs,user,password);
            st= con.createStatement();
            query="select Name,PhoneNo from seller where Name = '"+search1.getText()+"'";

            ResultSet rs = st.executeQuery(query);
            if(rs.first()){
                name1.setText(rs.getString("Name"));
                customerphone.setText(rs.getString("PhoneNo"));

            }
            else {
                JOptionPane.showMessageDialog(null, "No matching records found!");
                search1.setText("");
                name1.setText("");
                customerphone.setText("");
                search1.requestFocus();
            }
        }
        catch(SQLException  ex)
        {
        }
        catch( ClassNotFoundException ex)
        {
            
        }
        finally{
            try{
                if(st != null){
                    st.close();
                }
                if(con!=null){
                    con.close();
                }
            }
            catch(SQLException ex)
            {
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void previousmilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousmilkActionPerformed
         try       {
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection(cs,user,password);
                st=con.createStatement();
                query="select Name,PhoneNo  from seller";
                if(!next){  
                rs=st.executeQuery(query);
                prev=true;
                        } 
               
               
                                
       if(rs.previous()){
             search1.setText(rs.getString("Name"));
             name1.setText(rs.getString("Name"));
            customerphone.setText(rs.getString("PhoneNo")); 
            prev=true;
        
        } else{
              JOptionPane.showMessageDialog(null,"This is the last record no,prevoius record");
             
              }
                   }//end of try block
        
         catch(SQLException ex){ex.printStackTrace();}
       catch(ClassNotFoundException e){e.printStackTrace();}
// TODO add your handling code here:
    }//GEN-LAST:event_previousmilkActionPerformed

    private void nextmillkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextmillkActionPerformed
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            
            con=DriverManager.getConnection(cs,user,password);
            st= con.createStatement();
            
             query="select Name,PhoneNo  from seller";
             if(!next){
                 rs=st.executeQuery(query);
                 next=true;
                 
             }
           
         
            if(rs.next()){
             search1.setText(rs.getString("Name"));
             name1.setText(rs.getString("Name"));
            customerphone.setText(rs.getString("PhoneNo")); 
            next=true;
            }
            else {
            JOptionPane.showMessageDialog(null, "End of records!");
            }
        }
        catch(SQLException ex){ex.printStackTrace();}
       catch(ClassNotFoundException e){e.printStackTrace();}
// TODO add your handling code here:
    }//GEN-LAST:event_nextmillkActionPerformed

    private void ReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseClicked
        registerseller.setVisible(false);
        welcomelabel.setVisible(false);
        lnamelabel.setVisible(false);
         namelabel.setVisible(false);
        labelimage.setVisible(false);
        menubar.setVisible(false);
        viewseller.setVisible(false);
        // identity.setVisible(false);
          milk.setVisible(false);
          Reportpanel.setVisible(true);
          profilepanel.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportsMouseClicked

    private void RecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordsMouseClicked
       profilepanel.setVisible(false);
        registerseller.setVisible(false);
        welcomelabel.setVisible(false);
        lnamelabel.setVisible(false);
         namelabel.setVisible(false);
        labelimage.setVisible(false);
        menubar.setVisible(false);
        viewseller.setVisible(false);
         //identity.setVisible(false);
          milk.setVisible(true);
          Reportpanel.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_RecordsMouseClicked

    private void pricestandingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricestandingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricestandingActionPerformed

    private void statisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statisticsActionPerformed

    private void RegisteredSellersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisteredSellersMouseClicked
         pdfs pdf = new pdfs();
      pdf.name = usernamelabel.getText();
      pdf.fname = namelabel.getText();
      pdf.lastname = lnamelabel.getText();
      pdf.printreport(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_RegisteredSellersMouseClicked

    private void savemilkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savemilkMouseClicked
       String  custname = name1.getText();
       String phone = customerphone.getText();
       String day = currenttime.getText();
         String x = mng.getText();
         String y = even.getText();
         
         if (custname.isEmpty()|| phone.isEmpty()|| x.isEmpty()|| y.isEmpty()){
         JOptionPane.showMessageDialog(null, "Missing fields can't submit missing records ");
         }
         else{
         int morn = Integer.parseInt(x.trim());
         int evng = Integer.parseInt(y.trim());
         int total1 = morn + evng ;
         String total2 = Integer.toString(total1);
         total.setText(total2);
         String tot = total.getText();
         
             try{
                Class.forName("com.mysql.jdbc.Driver"); //registers drivers we configured
                con=DriverManager.getConnection(cs,user,password);
                st=con.createStatement();
                query = "INSERT INTO milkrecords(Day,CustomerName,PhoneNo,Litres) VALUES('"+day+"','" +custname+"','" +phone+"','" +tot+"')";
                st.executeUpdate(query);//executes the activities

                /*String  seequery= "select username from register where username='"+usernametxt.getText()+"'";*/

                /*ResultSet uname=  st.executeQuery(seequery);
                uname.getString("username");*/
                 JOptionPane.showMessageDialog(null, "Record Saved!");
                
            }
            catch(SQLException ex){
                ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt

            }
            catch(ClassNotFoundException ex){
                ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt

            }
            finally
            {
                try
                {
                    if (st!=null)
                    {
                        st.close();
                    }

                    if(con!=null)
                    {
                        con.close();
                    }
                }
                catch(SQLException ex){
                    ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt
                }

            }
           
        }
         
         
// TODO add your handling code here:
    }//GEN-LAST:event_savemilkMouseClicked

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseClicked
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(null);
        File f = choose.getSelectedFile();
         String filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage());
        //   Image myimg = im.getScaledInstance(profileimage.getWidth(), profile.getHeight(),Image.SCALE_SMOOTH);
        profileimage.setIcon(imageicon);
        try{
            File image= new File(filename);
            FileInputStream fis= new FileInputStream(image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum;(readNum = fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            byte[] person_image = bos.toByteArray();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_imageMouseClicked

    private void viewprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewprofileMouseClicked
        registerseller.setVisible(false);
        welcomelabel.setVisible(false);
        lnamelabel.setVisible(false);
         namelabel.setVisible(false);
        labelimage.setVisible(false);
        menubar.setVisible(false);
        viewseller.setVisible(false);
         //identity.setVisible(false);
          milk.setVisible(false);
          profilepanel.setVisible(true);
          Reportpanel.setVisible(false);
          
           try{
            Class.forName("com.mysql.jdbc.Driver");

            con=DriverManager.getConnection(cs,user,password);
            st= con.createStatement();
            query="select * from register where username = '"+name+"'";

            ResultSet rs = st.executeQuery(query);
            if(rs.first()){
                fname.setText(rs.getString("Fname"));
                lname.setText(rs.getString("Lname"));
                email.setText(rs.getString("Email"));
                dob.setText(rs.getString("DateOfBirth"));
                tel.setText(rs.getString("Telephone"));
                byte[] img = rs1.getBytes("profile");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myimg = im.getScaledInstance(profileimage.getWidth(), profileimage.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newimage = new ImageIcon(myimg);
                    profileimage.setIcon(newimage);
            }
            else {
                JOptionPane.showMessageDialog(null, "Action cant be completed!");
            }
        }
        catch(SQLException  ex)
        {
        }
        catch( ClassNotFoundException ex)
        {
            
        }
        finally{
            try{
                if(st != null){
                    st.close();
                }
                if(con!=null){
                    con.close();
                }
            }
            catch(SQLException ex)
            {
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_viewprofileMouseClicked

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        String s1=fname.getText();
        String s2=lname.getText();
        String s3=email.getText();
        String s4=dob.getText();
        String  s5=tel.getText();
        

        if(s1.equals("") || s2.equals("") || s3.equals("") || s4.equals("") ||s5.equals("")){
           JOptionPane.showMessageDialog(null,"Some missing fields");      
        }
        else {
        try{
                Class.forName("com.mysql.jdbc.Driver"); //registers drivers we configured
                con=DriverManager.getConnection(cs,user,password);
                st=con.createStatement();
                query="UPDATE  register set Fname = '"+s1+"',Lname= '"+s2+"',Email = '"+s3+"',DateOfBirth = '"+s4+"',Telephone= '"+s5+"' where username = '"+name+"'";
                st.executeUpdate(query);//executes the activities

                /*String  seequery= "select username from register where username='"+usernametxt.getText()+"'";*/

                /*ResultSet uname=  st.executeQuery(seequery);
                uname.getString("username");*/

                JOptionPane.showMessageDialog(null,"Updated  successfully!");
               
            }
            catch(ClassNotFoundException ex){
                ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt

            }
            catch(SQLException ex){
                ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt

            }
            finally
            {
                try
                {
                    if (st!=null)
                    {
                        st.close();
                    }

                    if(con!=null)
                    {
                        con.close();
                    }
                }
                catch(SQLException ex){
                    ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt
                }

            }
        
        
        }
// TODO add your handling code here:
    }//GEN-LAST:event_updatebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create a````````````````````````````````````````````````nd display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Reportpanel;
    private javax.swing.JLabel currenttime;
    private javax.swing.JLabel currenttime1;
    private javax.swing.JTextField customerphone;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField even;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel image;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelimage;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel lnamelabel;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menubar;
    private javax.swing.JPanel milk;
    private javax.swing.JTextField mng;
    private javax.swing.JLabel msgsell;
    private javax.swing.JLabel msgsell1;
    private javax.swing.JTextField name1;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profileimage;
    private javax.swing.JPanel profilepanel;
    private javax.swing.JPanel registerseller;
    private javax.swing.JTextField search1;
    private javax.swing.JTextField searchseller;
    private javax.swing.JTextField sellAddress;
    private javax.swing.JTextField sellname;
    private javax.swing.JTextField sellphone;
    private javax.swing.JTextField tel;
    private javax.swing.JLabel today;
    private javax.swing.JLabel today1;
    private javax.swing.JLabel today2;
    private javax.swing.JLabel today3;
    private javax.swing.JTextField total;
    public static javax.swing.JLabel usernamelabel;
    private javax.swing.JPanel viewseller;
    private javax.swing.JLabel welcomelabel;
    // End of variables declaration//GEN-END:variables
}
