/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ISOPHEL PC
 */
public class SignUp extends javax.swing.JFrame {
    String filename;
    Connection con;
    PreparedStatement statement;
    Statement st;
    String cs;
    boolean next;
    String password;

    String query;
    ResultSet rs;
    String user;
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        
            con = null;
        st = null;
        statement = null;
        next = false;
        cs = "jdbc:mysql://localhost:3306/dairy_project";

        password = "";
        user = "root";
        initComponents();
         
        this.setLocationRelativeTo(null);
    
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        fnamelabel = new javax.swing.JLabel();
        lnamelabel = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        lnametxt = new javax.swing.JTextField();
        emaillabel = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        Telelabel = new javax.swing.JLabel();
        phnetxt = new javax.swing.JTextField();
        doblabel = new javax.swing.JLabel();
        genderlabel = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        passwordlabel = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        confirmlabel = new javax.swing.JLabel();
        confirmpass = new javax.swing.JPasswordField();
        terms = new javax.swing.JCheckBox();
        termstxt = new javax.swing.JLabel();
        createbtn = new javax.swing.JLabel();
        messagelabel = new javax.swing.JLabel();
        valfname = new javax.swing.JLabel();
        vallastname = new javax.swing.JLabel();
        valemail = new javax.swing.JLabel();
        valphone = new javax.swing.JLabel();
        valusername = new javax.swing.JLabel();
        valpassword = new javax.swing.JLabel();
        valconfirm = new javax.swing.JLabel();
        confirm = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        profileimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainpanel.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Quality Organic Dairy");

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        image.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        image.setForeground(new java.awt.Color(0, 204, 102));
        image.setText("Upload profile_image");
        image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageMouseClicked(evt);
            }
        });

        fnamelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fnamelabel.setForeground(new java.awt.Color(0, 204, 102));
        fnamelabel.setText("First Name:");

        lnamelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lnamelabel.setForeground(new java.awt.Color(0, 204, 51));
        lnamelabel.setText("Last Name:");

        fnametxt.setBackground(new java.awt.Color(255, 255, 204));
        fnametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fnametxt.setForeground(new java.awt.Color(0, 204, 102));
        fnametxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 0)));
        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });

        lnametxt.setBackground(new java.awt.Color(255, 255, 204));
        lnametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lnametxt.setForeground(new java.awt.Color(0, 204, 51));
        lnametxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));

        emaillabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emaillabel.setForeground(new java.awt.Color(0, 204, 51));
        emaillabel.setText("Email Address:");

        emailtxt.setBackground(new java.awt.Color(255, 255, 204));
        emailtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(0, 255, 102));
        emailtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });

        Telelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Telelabel.setForeground(new java.awt.Color(0, 204, 51));
        Telelabel.setText("Telephone No.");

        phnetxt.setBackground(new java.awt.Color(255, 255, 204));
        phnetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phnetxt.setForeground(new java.awt.Color(0, 255, 102));
        phnetxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 0)));
        phnetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnetxtActionPerformed(evt);
            }
        });

        doblabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doblabel.setForeground(new java.awt.Color(0, 204, 0));
        doblabel.setText("Date of Birth:");

        genderlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genderlabel.setForeground(new java.awt.Color(0, 204, 51));
        genderlabel.setText("Gender:");

        usernamelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernamelabel.setForeground(new java.awt.Color(0, 204, 51));
        usernamelabel.setText("Username:");

        usernametxt.setBackground(new java.awt.Color(255, 255, 204));
        usernametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(0, 204, 51));
        usernametxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });

        passwordlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(0, 204, 51));
        passwordlabel.setText("Password:");

        passwordtxt.setBackground(new java.awt.Color(255, 255, 204));
        passwordtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(0, 204, 102));
        passwordtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });

        confirmlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmlabel.setForeground(new java.awt.Color(0, 204, 51));
        confirmlabel.setText("Confirm-Password:");

        confirmpass.setBackground(new java.awt.Color(255, 255, 204));
        confirmpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmpass.setForeground(new java.awt.Color(0, 255, 102));
        confirmpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 51)));
        confirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassActionPerformed(evt);
            }
        });

        terms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        termstxt.setBackground(new java.awt.Color(255, 255, 255));
        termstxt.setFont(new java.awt.Font("Sitka Small", 2, 14)); // NOI18N
        termstxt.setForeground(new java.awt.Color(0, 204, 102));
        termstxt.setText("\" By clicking you Agree the Terms and Conditions\"");

        createbtn.setBackground(new java.awt.Color(73, 102, 70));
        createbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        createbtn.setForeground(new java.awt.Color(0, 204, 51));
        createbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createbtn.setText("SignUp");
        createbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102)));
        createbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createbtnMouseClicked(evt);
            }
        });

        messagelabel.setBackground(new java.awt.Color(255, 255, 204));
        messagelabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        messagelabel.setForeground(new java.awt.Color(255, 51, 0));
        messagelabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                messagelabelKeyPressed(evt);
            }
        });

        valfname.setBackground(new java.awt.Color(255, 255, 204));
        valfname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valfname.setForeground(new java.awt.Color(255, 51, 51));
        valfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valfnameKeyPressed(evt);
            }
        });

        vallastname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vallastname.setForeground(new java.awt.Color(255, 102, 0));

        valemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valemail.setForeground(new java.awt.Color(255, 102, 51));

        valphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valphone.setForeground(new java.awt.Color(255, 153, 0));

        valusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valusername.setForeground(new java.awt.Color(255, 153, 0));

        valpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valpassword.setForeground(new java.awt.Color(255, 102, 0));

        valconfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valconfirm.setForeground(new java.awt.Color(255, 153, 0));

        confirm.setBackground(new java.awt.Color(255, 255, 204));
        confirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 51, 0));

        date.setBackground(new java.awt.Color(255, 255, 204));
        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        profileimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/user.png"))); // NOI18N
        profileimage.setText("jLabel2");

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainpanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(mainpanelLayout.createSequentialGroup()
                                                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                                        .addGap(22, 22, 22)
                                                        .addComponent(fnamelabel))
                                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                                        .addGap(31, 31, 31)
                                                        .addComponent(genderlabel))
                                                    .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Telelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(mainpanelLayout.createSequentialGroup()
                                                            .addGap(18, 18, 18)
                                                            .addComponent(lnamelabel)))
                                                    .addComponent(passwordlabel)
                                                    .addComponent(confirmlabel))
                                                .addGap(23, 23, 23)
                                                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                                        .addComponent(phnetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(valphone, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(valconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(mainpanelLayout.createSequentialGroup()
                                                                .addGap(98, 98, 98)
                                                                .addComponent(profileimage, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                                                        .addGap(80, 80, 80)
                                                                        .addComponent(valfname, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                                                        .addGap(29, 29, 29)
                                                                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                            .addComponent(fnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(mainpanelLayout.createSequentialGroup()
                                                                .addComponent(lnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(vallastname, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(mainpanelLayout.createSequentialGroup()
                                                                    .addGap(79, 79, 79)
                                                                    .addComponent(createbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(mainpanelLayout.createSequentialGroup()
                                                                    .addComponent(confirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(21, 21, 21)
                                                                    .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(valusername, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                        .addGap(0, 0, Short.MAX_VALUE))))
                                            .addGroup(mainpanelLayout.createSequentialGroup()
                                                .addGap(92, 92, 92)
                                                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(messagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(terms)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(termstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, Short.MAX_VALUE))
                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(mainpanelLayout.createSequentialGroup()
                                                .addComponent(emaillabel)
                                                .addGap(27, 27, 27)
                                                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(valemail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(usernamelabel)
                                            .addGroup(mainpanelLayout.createSequentialGroup()
                                                .addComponent(doblabel)
                                                .addGap(40, 40, 40)
                                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(mainpanelLayout.createSequentialGroup()
                                .addGap(414, 414, 414)
                                .addComponent(valpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileimage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainpanelLayout.createSequentialGroup()
                                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(fnamelabel)
                                            .addComponent(fnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(valfname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)
                                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vallastname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lnamelabel))
                                .addGap(4, 4, 4)
                                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emaillabel)
                                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainpanelLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(valemail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phnetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telelabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(valphone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doblabel)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(genderlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernamelabel)
                            .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(valusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordlabel)
                        .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(valpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(confirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(messagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(termstxt))
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(terms)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(valconfirm)
                .addGap(189, 189, 189))
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseClicked
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(null);
        File f = choose.getSelectedFile();
       filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage());
          //   Image myimg = im.getScaledInstance(profileimage.getWidth(), profile.getHeight(),Image.SCALE_SMOOTH);
        profileimage.setIcon(imageicon);
        try{
            File image= new File(filename);
            FileInputStream fis= new FileInputStream(image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum;(readNum = fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            byte[] person_image = bos.toByteArray();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_imageMouseClicked

    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void phnetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnetxtActionPerformed

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void confirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassActionPerformed

    private void createbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbtnMouseClicked

        String s1=fnametxt.getText();
        String s2=lnametxt.getText();
        String s3=emailtxt.getText();
        String s4=phnetxt.getText();
        String  s5=date.getText();
        String s6=gender.getSelectedItem().toString();
        String s7= usernametxt.getText();
        String s8=passwordtxt.getText().toString();
        String s9=confirmpass.getText().toString();
      
        ImageIcon icon = new ImageIcon(filename);
        Image profile = icon.getImage();

        if(s1.equals("") && s2.equals("") && s3.equals("") && s4.equals("") &&  s7.equals("") && s8.equals("") && s9.equals("")){
            messagelabel.setText("All Entries must be filled correctly!");
            fnametxt.requestFocus();
        }
        else if(s1.equals("")){
            valfname.setText("*Recqiured");
            fnametxt.requestFocus();
        }
        else if(s2.equals("")){
            vallastname.setText("*Recquired");
            lnametxt.requestFocus();
        }
        else if(s3.equals("")){
            valemail.setText("*Recquired");
            emailtxt.requestFocus();
        }
        else if(s4.equals("")){
            valphone.setText("*Recquired");
            phnetxt.requestFocus();
        }
        else if(s8.equals("") ){
            valpassword.setText("*Recquired");
            passwordtxt.requestFocus();
        }
        else if(s7.equals("")){
            valusername.setText("*Recquired");
            usernametxt.requestFocus();

        }
        else if(!s9.equals(s8)){
            confirm.setText("password mismatch!");
            confirmpass.requestFocus();

        }

        else{

            try{
                Class.forName("com.mysql.jdbc.Driver"); //registers drivers we configured
                con=DriverManager.getConnection(cs,user,password);
                st=con.createStatement();
                query="INSERT INTO register(Fname,Lname,Email,Telephone,DateOfBirth,gender,username,password,profile) VALUES('"+s1+"', '" +s2+"','" +s3+"','" +s4+"','" +s5+"','" +s6+"','" +s7+"','" +s8+"','" +profile+"')";
                st.executeUpdate(query);//executes the activities

                /*String  seequery= "select username from register where username='"+usernametxt.getText()+"'";*/

                /*ResultSet uname=  st.executeQuery(seequery);
                uname.getString("username");*/

                JOptionPane.showMessageDialog(null,"Account created successfully,continue");
                fnametxt.setText("");
                lnametxt.setText("");
                emailtxt.requestFocus();
                phnetxt.requestFocus();
                usernametxt.setText("");
                passwordtxt.setText("");
                confirmpass.setText("");
                emailtxt.setText("");
                phnetxt.setText("");
                fnametxt.requestFocus();
                lnametxt.requestFocus();
                usernametxt.requestFocus();
                passwordtxt.requestFocus();
                confirmpass.requestFocus();
            }
            catch(ClassNotFoundException ex){
                ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt

            }
            catch(SQLException ex){
                ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt

            }
            finally
            {
                try
                {
                    if (st!=null)
                    {
                        st.close();
                    }

                    if(con!=null)
                    {
                        con.close();
                    }
                }
                catch(SQLException ex){
                    ex.printStackTrace();//mtd that tells what has happened at the time of execution of that stattmt
                }

            }
            login hme =  new login();
            hme.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_createbtnMouseClicked

    private void messagelabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messagelabelKeyPressed
        // TODO add your handling code here:
        messagelabel.setText("");
    }//GEN-LAST:event_messagelabelKeyPressed

    private void valfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valfnameKeyPressed
        // TODO add your handling code here:
        valfname.setText("");
    }//GEN-LAST:event_valfnameKeyPressed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        this.dispose();
        login log = new login();
        log.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               new SignUp().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Telelabel;
    private javax.swing.JLabel confirm;
    private javax.swing.JLabel confirmlabel;
    private javax.swing.JPasswordField confirmpass;
    private javax.swing.JLabel createbtn;
    private javax.swing.JTextField date;
    private javax.swing.JLabel doblabel;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel fnamelabel;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lnamelabel;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLabel messagelabel;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField phnetxt;
    private javax.swing.JLabel profileimage;
    private javax.swing.JCheckBox terms;
    private javax.swing.JLabel termstxt;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JLabel valconfirm;
    private javax.swing.JLabel valemail;
    private javax.swing.JLabel valfname;
    private javax.swing.JLabel vallastname;
    private javax.swing.JLabel valpassword;
    private javax.swing.JLabel valphone;
    private javax.swing.JLabel valusername;
    // End of variables declaration//GEN-END:variables
}
